version: "3.1"

services:
  mongo:
    image:  mongodb/mongodb-community-server
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    volumes:
      - ./db_data/:/data/db/